"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
"""
Django settings for config project.

Для Django Oscar 4.x
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# from oscar import get_core_apps

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    # Стандартные приложения Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Важные пакеты для Oscar
   'django.contrib.flatpages', # Часто требуется Oscar
    # --- НАЧИНАЕМ РУЧНОЙ СПИСОК ПРИЛОЖЕНИЙ OSCAR ---
    # Обязательные приложения (в строгом порядке)
    # --- ТОЛЬКО СИСТЕМНЫЕ ПРИЛОЖЕНИЯ OSCAR ---
    # (Мы подключаем их все вручную, чтобы избежать багов автозагрузки)
    # 'oscar.apps.analytics.apps.AnalyticsConfig',
    # 'oscar.apps.checkout.apps.CheckoutConfig',
    # 'oscar.apps.address.apps.AddressConfig',
    # 'oscar.apps.shipping.apps.ShippingConfig',
    # 'oscar.apps.catalogue.apps.CatalogueConfig',
    # 'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
    # 'oscar.apps.communication.apps.CommunicationConfig',
    # 'oscar.apps.partner.apps.PartnerConfig',
    # 'oscar.apps.basket.apps.BasketConfig',
    # 'oscar.apps.payment.apps.PaymentConfig',
    # 'oscar.apps.offer.apps.OfferConfig',
    # 'oscar.apps.order.apps.OrderConfig',
    # 'oscar.apps.customer.apps.CustomerConfig',
    # 'oscar.apps.search.apps.SearchConfig',
    # 'oscar.apps.voucher.apps.VoucherConfig',
    # 'oscar.apps.wishlists.apps.WishlistsConfig',
    # 'oscar.apps.dashboard.apps.DashboardConfig',
    # 'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
    # 'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
    # 'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
    # 'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
    # 'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
    # 'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
    # Остальные приложения Dashboard можно не указывать, если они не используются.
    # --- ГЛАВНАЯ СТРОКА ЗАГРУЗКИ OSCAR ---
    # Стало:
    # get_core_apps(),
    # 'oscar.config.Shop', 
    # Приложение Каталога (ОБЯЗАТЕЛЬНО для Oscar 4.x)
    'oscar.apps.catalogue.apps.CatalogueConfig',
    'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
    # 'oscar.apps.customer.apps.CustomerConfig',
    
    'oscar.apps.customer.apps.CustomerConfig',
    'oscar.apps.communication.apps.CommunicationConfig',
    
    'oscar.apps.partner.apps.PartnerConfig',
    # 'oscar.apps.analytics.apps.AnalyticsConfig', 
    # 'apps.analytics.apps',    # Модуль Поиска (Search) и его фичи
    'oscar.apps.search.apps.SearchConfig', # <-- ДОБАВЬТЕ ЭТУ СТРОКУ
    'oscar.apps.offer.apps.OfferConfig', 
    'oscar.apps.wishlists.apps.WishlistsConfig',
    # --- КОРЗИНА (BASKET) - ОБЯЗАТЕЛЬНО ---
    'oscar.apps.shipping.apps.ShippingConfig',
    'oscar.apps.checkout.apps.CheckoutConfig',
    'oscar.apps.payment.apps.PaymentConfig',
    'oscar.apps.voucher.apps.VoucherConfig',
    'oscar.apps.basket.apps.BasketConfig',
    
    
    'oscar.apps.order.apps.OrderConfig',
    'oscar.apps.address.apps.AddressConfig',
    
    # Приложение-пустышка для Dashboard
    'catalogue_dashboard', 
    'reports_dashboard',
    'orders_dashboard',
    'users_dashboard',
    'pages_dashboard',
    'partners_dashboard',
    'offers_dashboard',
    'ranges_dashboard', 
    'reviews_dashboard', 
    'vouchers_dashboard',
    'communications_dashboard',
    'shipping_dashboard',
    
    # Зависимости
    'haystack',
    
    # # Приложение Oscar (это загрузит все необходимые приложения автоматически)
    # 'oscar.config.Shop',
    
    # Панель управления (Dashboard)
    'oscar.apps.dashboard.apps.DashboardConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Для статики (рекомендуется)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# Database (остается без изменений)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST", "db"), # Имя сервиса из docker-compose
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'ru-ru' # Или 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Путь для collectstatic

# Настройки Oscar (начинаются здесь)
# Настройки поиска через Haystack (для Oscar)
# Подключаемся к нашему OpenSearch сервису из docker-compose
HAYSTACK_CONNECTIONS = {
    'default': {
        # Используем бэкенд для Elasticsearch 7.x
        'ENGINE': 'haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine',
        # URL к контейнеру с OpenSearch
        'URL': ['http://search:9200'],
        # Название индекса в OpenSearch
        'INDEX_NAME': 'oscar',
    },
}
# Поиск (OpenSearch / Elasticsearch)
# Новая структура настроек поиска (для Oscar 4.x)
OSCAR_SEARCH = {
    "MODEL": "catalogue.Product",
    "HANDLER": "oscar.apps.search.handlers.CatalogueSearchHandler",
    # В версии 4.x 'FACETS' находится внутри 'QUERY'
    "QUERY": {
        "FACETS": {
            "fields": {},
            "queries": {},
        }
    },
}
# --- ЭМУЛЯЦИЯ СТАРОГО API ДЛЯ СОВМЕСТИМОСТИ С OSCAR 4.1.1 ---
# Эта настройка "обманет" старый код в oscar/apps/search/forms.py
# Она скажет: "У меня есть словарь OSCAR_SEARCH_FACETS, и внутри него есть ключ 'queries'"
# Мы просто свяжем его с новой структурой.
# Теперь мы берем данные из нового места: OSCAR_SEARCH["QUERY"]["FACETS"]
OSCAR_SEARCH_FACETS = {
    "fields": OSCAR_SEARCH["QUERY"]["FACETS"]["fields"],
    "queries": OSCAR_SEARCH["QUERY"]["FACETS"]["queries"],
}
# Корзина и оформление заказа
OSCAR_ALLOW_ANON_CHECKOUT = True

# Адреса
OSCAR_REQUIRED_ADDRESS_FIELDS = ('first_name', 'last_name', 'line1', 'line4', 'postcode', 'country')

# Шаблоны (стало проще)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Ваши кастомные шаблоны
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                *(
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ),
                # Контекстные процессоры Oscar (стандартный набор)
                ('oscar.apps.search.context_processors.search_form'),
                ('oscar.apps.checkout.context_processors.checkout'),
                # ('oscar.apps.customer.notifications.context_processors.notifications'),
                ('oscar.core.context_processors.metadata'),
            ],
        },
    },
]
# Используйте BigAutoField для всех новых моделей по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Эта настройка нужна для совместимости с Oscar 4.1.x
# Она указывает использовать стандартный механизм загрузки классов Django.
OSCAR_DYNAMIC_CLASS_LOADER = 'oscar.core.loading.default_class_loader'
# Эта настройка нужна для совместимости с Oscar 4.1.x
# Она разрешает использовать юникод (кириллицу) в слагах (URL).
OSCAR_SLUG_ALLOW_UNICODE = True
# Эта настройка нужна для совместимости с Oscar 4.1.x
# Она отвечает за удаление файлов изображений с диска при удалении товара.
OSCAR_DELETE_IMAGE_FILES = True
# Количество товаров на странице (для совместимости с Oscar 4.1.1)
OSCAR_PRODUCTS_PER_PAGE = 20
# Количество предложений (офферов) на странице
OSCAR_OFFERS_PER_PAGE = 20
# Количество отзывов на странице
OSCAR_REVIEWS_PER_PAGE = 20
# Имя куки для хранения истории просмотренных товаров
OSCAR_RECENTLY_VIEWED_COOKIE_NAME = 'oscar_history'
# Время жизни куки с историей просмотров (в секундах)
# 1 неделя = 7 дней * 24 часа * 60 минут * 60 секунд
OSCAR_RECENTLY_VIEWED_COOKIE_LIFETIME = 7 * 24 * 60 * 60
# Отключаем требование HTTPS для куки истории просмотров (для разработки)
OSCAR_RECENTLY_VIEWED_COOKIE_SECURE = False
# Сколько последних просмотренных товаров хранить
OSCAR_RECENTLY_VIEWED_PRODUCTS = 20
# Настройка для отправки оповещений (требуется для запуска)
OSCAR_EAGER_ALERTS = True
# URL, на который перенаправлять пользователя после входа в личный кабинет
OSCAR_ACCOUNTS_REDIRECT_URL = 'customer:profile-view'
# Главная страница магазина (URL name)
OSCAR_HOMEPAGE = 'promotions:home'
# Количество писем в истории на странице личного кабинета
OSCAR_EMAILS_PER_PAGE = 20
# Количество заказов в истории на странице личного кабинета
OSCAR_ORDERS_PER_PAGE = 20
# Количество адресов на странице в личном кабинете
OSCAR_ADDRESSES_PER_PAGE = 10
# Количество уведомлений на странице в личном кабинете
OSCAR_NOTIFICATIONS_PER_PAGE = 10
# Название магазина
OSCAR_SHOP_NAME = "Stroymir"
# Слоган магазина (подзаголовок)
OSCAR_SHOP_TAGLINE = "Современный интернет-магазин на Django"
