"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
"""
Django settings for config project.

Для Django Oscar 4.x
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    'oscar.config.Shop',
    'oscar.apps.analytics.apps.AnalyticsConfig',
    'oscar.apps.checkout.apps.CheckoutConfig',
    'oscar.apps.address.apps.AddressConfig',
    'oscar.apps.shipping.apps.ShippingConfig',
    'oscar.apps.catalogue.apps.CatalogueConfig',
    'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
    'oscar.apps.communication.apps.CommunicationConfig',
    'oscar.apps.partner.apps.PartnerConfig',
    'oscar.apps.basket.apps.BasketConfig',
    'oscar.apps.payment.apps.PaymentConfig',
    'oscar.apps.offer.apps.OfferConfig',
    'oscar.apps.order.apps.OrderConfig',
    'oscar.apps.customer.apps.CustomerConfig',
    'oscar.apps.search.apps.SearchConfig',
    'oscar.apps.voucher.apps.VoucherConfig',
    'oscar.apps.wishlists.apps.WishlistsConfig',
    'oscar.apps.dashboard.apps.DashboardConfig',
    'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
    'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
    'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
    'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
    'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
    'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
    'oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
    'oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
    'oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig',
    'oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
    'oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
    'oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',

    # 3rd-party apps that Oscar depends on
    'widget_tweaks',
    'haystack',
    'treebeard',
    'sorl.thumbnail',
    'easy_thumbnails',
    'django_tables2',

    # Django apps that the sandbox depends on
    'django.contrib.sitemaps',
]
# INSTALLED_APPS = [
#     # Django core apps
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.sites",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     'django.contrib.flatpages',

#     # Oscar dependencies
#     'haystack',
#     'widget_tweaks',

#     # Oscar core apps (ВАЖНО: Строгий порядок!)
#     'oscar.apps.analytics.apps.AnalyticsConfig',
#     'oscar.apps.checkout.apps.CheckoutConfig',
#     'oscar.apps.address.apps.AddressConfig',
#     'oscar.apps.shipping.apps.ShippingConfig',
#     'oscar.apps.catalogue.apps.CatalogueConfig',
    
#     'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
#     'oscar.apps.communication.apps.CommunicationConfig',
#     'oscar.apps.partner.apps.PartnerConfig',
#     'oscar.apps.basket.apps.BasketConfig',
#     'oscar.apps.payment.apps.PaymentConfig',
#     'oscar.apps.offer.apps.OfferConfig',
#     'oscar.apps.order.apps.OrderConfig',
#     'oscar.apps.customer.apps.CustomerConfig',
#     'oscar.apps.search.apps.SearchConfig',
#     'oscar.apps.voucher.apps.VoucherConfig',
#     'oscar.apps.wishlists.apps.WishlistsConfig',
    
#     # Oscar dashboard apps
#     'oscar.apps.dashboard.apps.DashboardConfig',
#     'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
#     'oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
#     'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
#     'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
#     'oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
#     'oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig', 
#     'oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
#     'oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',
#     'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
#     'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
#     'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
#     'oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
    
#         # Приложение-пустышка для Dashboard
#     # 'catalogue_dashboard', 
#     # 'reports_dashboard',
#     # 'orders_dashboard',
#     # 'users_dashboard',
#     # 'pages_dashboard',
#     # 'partners_dashboard',
#     # 'offers_dashboard',
#     # 'ranges_dashboard', 
#     # 'reviews_dashboard', 
#     # 'vouchers_dashboard',
#     # 'communications_dashboard',
#     # 'shipping_dashboard',
# ]
# INSTALLED_APPS = [
#     # Стандартные приложения Django
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.sites",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     # Важные пакеты для Oscar
#    'django.contrib.flatpages', # Часто требуется Oscar
#     'oscar', # Основной пакет Oscar
#     # Приложение Каталога (ОБЯЗАТЕЛЬНО для Oscar 4.x)
#     'oscar.apps.catalogue.apps.CatalogueConfig',
#     'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
#     # 'oscar.apps.customer.apps.CustomerConfig',
    
#     'oscar.apps.customer.apps.CustomerConfig',
#     'oscar.apps.communication.apps.CommunicationConfig',
    
#     'oscar.apps.partner.apps.PartnerConfig',
#     'oscar.apps.analytics.apps.AnalyticsConfig', 
#     # 'apps.analytics.apps',    # Модуль Поиска (Search) и его фичи
#     'oscar.apps.search.apps.SearchConfig', # <-- ДОБАВЬТЕ ЭТУ СТРОКУ
#     'oscar.apps.offer.apps.OfferConfig', 
#     'oscar.apps.wishlists.apps.WishlistsConfig',
#     # --- КОРЗИНА (BASKET) - ОБЯЗАТЕЛЬНО ---
#     'oscar.apps.shipping.apps.ShippingConfig',
#     'oscar.apps.checkout.apps.CheckoutConfig',
#     'oscar.apps.payment.apps.PaymentConfig',
#     'oscar.apps.voucher.apps.VoucherConfig',
#     'oscar.apps.basket.apps.BasketConfig',
    
    
#     'oscar.apps.order.apps.OrderConfig',
#     'oscar.apps.address.apps.AddressConfig',
    
#     # Приложение-пустышка для Dashboard
#     'catalogue_dashboard', 
#     'reports_dashboard',
#     'orders_dashboard',
#     'users_dashboard',
#     'pages_dashboard',
#     'partners_dashboard',
#     'offers_dashboard',
#     'ranges_dashboard', 
#     'reviews_dashboard', 
#     'vouchers_dashboard',
#     'communications_dashboard',
#     'shipping_dashboard',
    
#     # Зависимости
#     'haystack',
    
#     # # Приложение Oscar (это загрузит все необходимые приложения автоматически)
#     # 'oscar.config.Shop',
    
#     # Панель управления (Dashboard)
#     'oscar.apps.dashboard.apps.DashboardConfig',
# ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Для статики (рекомендуется)
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'oscar.middleware.basket.BasketMiddleware',
]

ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# Database (остается без изменений)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST", "db"), # Имя сервиса из docker-compose
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'ru-ru' # Или 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Путь для collectstatic

# Настройки Oscar (начинаются здесь)
# settings.py (БЛОК ПОИСКА)
# Функция для удобного построения путей
BASE_DIR = Path(__file__).resolve().parent.parent.parent # или как у вас определено

def location(x):
    return os.path.join(BASE_DIR, x)

# --- НАСТРОЙКИ ПОИСКА HAYSTACK ---
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

HAYSTACK_CONNECTIONS = {
    'default': {
        # Используем движок Whoosh. Ему НЕ НУЖЕН ВНЕШНИЙ СЕРВЕР!
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # Путь к папке, где Whoosh будет хранить свои файлы индекса
        'PATH': location('whoosh_index'),
        'INCLUDE_SPELLING': True, # Включаем подсказки "возможно, вы имели в виду..."
    },
}
# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine',
#         'URL': 'http://search:9200/', # <-- ИСПРАВЛЕНО ИМЯ СЕРВИСА
#         'INDEX_NAME': 'haystack',
#         'TIMEOUT': 60 * 5,
#         'USE_SSL': False,
#         'VERIFY_SSL': False,
#     },
# }
# Настройка для автоматической синхронизации БД и поиска
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# # Настройки поиска через Haystack (для Oscar)
# # Подключаемся к нашему OpenSearch сервису из docker-compose
# HAYSTACK_CONNECTIONS = {
#     'default': {
#         # Используем бэкенд для Elasticsearch 7.x
#         'ENGINE': 'haystack.backends.elasticsearch7_backend.Elasticsearch7SearchEngine',
#         # URL к контейнеру с OpenSearch
#         'URL': ['http://search:9200'],
#         # Название индекса в OpenSearch
#         'INDEX_NAME': 'oscar',
#     },
# }
# Поиск (OpenSearch / Elasticsearch)
# Новая структура настроек поиска (для Oscar 4.x)
OSCAR_SEARCH = {
    "MODEL": "catalogue.Product",
    "HANDLER": "oscar.apps.search.handlers.CatalogueSearchHandler",
    # В версии 4.x 'FACETS' находится внутри 'QUERY'
    "QUERY": {
        "FACETS": {
            "fields": {},
            "queries": {},
        }
    },
}
# --- ЭМУЛЯЦИЯ СТАРОГО API ДЛЯ СОВМЕСТИМОСТИ С OSCAR 4.1.1 ---
# Эта настройка "обманет" старый код в oscar/apps/search/forms.py
# Она скажет: "У меня есть словарь OSCAR_SEARCH_FACETS, и внутри него есть ключ 'queries'"
# Мы просто свяжем его с новой структурой.
# Теперь мы берем данные из нового места: OSCAR_SEARCH["QUERY"]["FACETS"]
OSCAR_SEARCH_FACETS = {
    "fields": OSCAR_SEARCH["QUERY"]["FACETS"]["fields"],
    "queries": OSCAR_SEARCH["QUERY"]["FACETS"]["queries"],
}
# Корзина и оформление заказа
OSCAR_ALLOW_ANON_CHECKOUT = True

# Адреса
OSCAR_REQUIRED_ADDRESS_FIELDS = ('first_name', 'last_name', 'line1', 'line4', 'postcode', 'country')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            location('templates'),
        ],
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',
                
                # Oscar specific
                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.communication.notifications.context_processors.notifications',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.core.context_processors.metadata',
            ],
            'debug': DEBUG,
        }
    }
]

# Шаблоны (стало проще)
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')], # Ваши кастомные шаблоны
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 *(
#                     'django.template.context_processors.debug',
#                     'django.template.context_processors.request',
#                     'django.contrib.auth.context_processors.auth',
#                     'django.contrib.messages.context_processors.messages',
#                 ),
#                 # Контекстные процессоры Oscar (стандартный набор)
#                 ('oscar.apps.search.context_processors.search_form'),
#                 ('oscar.apps.checkout.context_processors.checkout'),
#                 # ('oscar.apps.customer.notifications.context_processors.notifications'),
#                 ('oscar.core.context_processors.metadata'),
#             ],
#         },
#     },
# ]
# Используйте BigAutoField для всех новых моделей по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Эта настройка нужна для совместимости с Oscar 4.1.x
# Она указывает использовать стандартный механизм загрузки классов Django.
OSCAR_DYNAMIC_CLASS_LOADER = 'oscar.core.loading.default_class_loader'
# Эта настройка нужна для совместимости с Oscar 4.1.x
# Она разрешает использовать юникод (кириллицу) в слагах (URL).
OSCAR_SLUG_ALLOW_UNICODE = True
# Эта настройка нужна для совместимости с Oscar 4.1.x
# Она отвечает за удаление файлов изображений с диска при удалении товара.
OSCAR_DELETE_IMAGE_FILES = True
# Количество товаров на странице (для совместимости с Oscar 4.1.1)
OSCAR_PRODUCTS_PER_PAGE = 20
# Количество предложений (офферов) на странице
OSCAR_OFFERS_PER_PAGE = 20
# Количество отзывов на странице
OSCAR_REVIEWS_PER_PAGE = 20
# Имя куки для хранения истории просмотренных товаров
OSCAR_RECENTLY_VIEWED_COOKIE_NAME = 'oscar_history'
# Время жизни куки с историей просмотров (в секундах)
# 1 неделя = 7 дней * 24 часа * 60 минут * 60 секунд
OSCAR_RECENTLY_VIEWED_COOKIE_LIFETIME = 7 * 24 * 60 * 60
# Отключаем требование HTTPS для куки истории просмотров (для разработки)
OSCAR_RECENTLY_VIEWED_COOKIE_SECURE = False
# Сколько последних просмотренных товаров хранить
OSCAR_RECENTLY_VIEWED_PRODUCTS = 20
# Настройка для отправки оповещений (требуется для запуска)
OSCAR_EAGER_ALERTS = True
# URL, на который перенаправлять пользователя после входа в личный кабинет
OSCAR_ACCOUNTS_REDIRECT_URL = 'customer:profile-view'
# Главная страница магазина (URL name)
# Указываем абсолютный путь к каталогу товаров (витрине)
OSCAR_HOMEPAGE = '/catalogue/'
# Количество писем в истории на странице личного кабинета
OSCAR_EMAILS_PER_PAGE = 20
# Количество заказов в истории на странице личного кабинета
OSCAR_ORDERS_PER_PAGE = 20
# Количество адресов на странице в личном кабинете
OSCAR_ADDRESSES_PER_PAGE = 10
# Количество уведомлений на странице в личном кабинете
OSCAR_NOTIFICATIONS_PER_PAGE = 10
# Название магазина
OSCAR_SHOP_NAME = "Stroymir"
# Слоган магазина (подзаголовок)
OSCAR_SHOP_TAGLINE = "Современный интернет-магазин на Django"
# Количество элементов на странице в панели управления (Dashboard)
OSCAR_DASHBOARD_ITEMS_PER_PAGE = 20
# Количество оповещений о стоке на странице в панели управления
OSCAR_STOCK_ALERTS_PER_PAGE = 20
OSCAR_HIDDEN_FEATURES = []  # Можно добавить нужные фичи для скрытия

# Пример скрытия некоторых функций:
# OSCAR_HIDDEN_FEATURES = [
#     'REVIEWS',
#     'WISHLISTS',
#     'PRODUCT_REVIEWS'
# ]